- mesures/a5d.py
- mesures/agrecl.py
- mesures/almacenacau.py
- mesures/autoconsumo.py
- mesures/b5d.py
- mesures/cilcau.py
- mesures/cupscau.py
- mesures/f1.py
- mesures/f5.py
- mesures/f5d.py
- mesures/p1.py
- mesures/p1d.py
- mesures/p2.py
- mesures/p2d.py
- mesures/p5d.py
- mesures/parsers/dummy_data.py
- mesures/pmest.py
- requirements.txt
- spec/generation_files_spec.py
Añadir posibilidad de comprimir o no un fichero. Anteriormente solo comprimía en BZ2
- todo: Añadir `isinstance(s, string_types)` como https://stackoverflow.com/questions/11301138/how-to-check-if-variable-is-string-with-python-2-and-3-compatibility para mantener compatibilidad a la hora de revisar: https://github.com/gisce/mesures/blob/fe516cf05b293be9b75605707c5d34a55e1f86f4/mesures/parsers/dummy_data.py#L35
- todo: Añadir al `requirements.txt` la librería `six`: https://github.com/gisce/mesures/blob/fe516cf05b293be9b75605707c5d34a55e1f86f4/requirements.txt#L4
> IMP añadir selección de compresión

- mesures/almacenacau.py
- En el fichero `Ficheros para el intercambio de información de medida`, se establece que la tecnología de almacenamiento se informa con dos carácteres.
- Por contra, en el fichero `Tratamiento de datos estructurales y de medidas de instalaciones de autoconsumo` se contradice esta información estableciendo los códigos de la tecnología en formato de un único carácter.
- Tras enviar ficheros `ALMACENACAU` al Concentrador Secundario, se ha visto que se procesan correctamente si se informa la tecnología con los códigos de un único carácter en lugar de dos.
> Correcciones en la generación del fichero ALMACENACAU

- .github/workflows/python3.6-app.yml
- mesures/mcil345.py
- Adaptar la generación del fichero `MCIL345` para que la curva se genere en tramos diarios.
- El fichero resultante era un único fichero.
- El fichero resultante es un fichero comprimido en formato ZIP que incluye los ficheros planos diarios.
- From https://github.com/gisce/erp/issues/15388
> Mejoras en el formato del fichero MCIL345

- mesures/a5d.py
- mesures/agrecl.py
- mesures/almacenacau.py
- mesures/autoconsumo.py
- mesures/b5d.py
- mesures/cilcau.py
- mesures/cildat.py
- mesures/cumpelectro.py
- mesures/cups45.py
- mesures/cupscau.py
- mesures/cupsdat.py
- mesures/cupselectro.py
- mesures/enelectroaut.py
- mesures/f1.py
- mesures/f3.py
- mesures/f5.py
- mesures/f5d.py
- mesures/mcil345.py
- mesures/medidas.py
- mesures/p1.py
- mesures/p1d.py
- mesures/p2.py
- mesures/p2d.py
- mesures/p5d.py
- mesures/pmest.py
- mesures/potelectro.py
- Se ha añadido el soporte para especificar el número de versión en la generación de ficheros (0 por defecto).
- El fichero `MCIL345` versiona los ficheros incluidos en el "zip" que retorna su generación.
> Soporte para versionado

- mesures/cupsdat.py
- mesures/mcil345.py
- Los ficheros `CUPSDAT` y `CUPS45` se versionan automáticamente si en el directorio temporal donde se generan ya existen ficheros del mismo tipo para el mismo periodo.
From https://github.com/gisce/erp/issues/15388
> Soporte para versionado en los ficheros CUPSDAT y CUPS45

- mesures/p1d.py
- spec/generation_files_spec.py
- Corregir el formato de salida del fichero `P1D`.
- El P1D se formatea como fichero ZIP con ficheros diarios en su interior (planos o comprimidos en `.bz2` según se requiera).
- El P1D se formatea como único fichero (plano o comprimido en `.bz2` según se requiera).
> Correcciones en el formato del fichero P1D

- mesures/f5.py
- mesures/f5d.py
- Si el contenido se lee desde una ruta y no desde una lista de diccionarios, se añade una columna extra para el delimitador de línea final (`;`), así el orden y la asociación de las columnas se mantienen en el DataFrame.
> Mejoras en la exportación de F5D cuando la información se lee desde fichero temporal

- mesures/autoconsumo.py
- No dejar vacíos los campos que informan de los números de registro MITECO, provisional y definitivo.
- Los campos se dejan vacíos.
- Los campos se llenan con la información de los autoconsumos.
- Closes #https://github.com/gisce/erp/issues/16340
> Correcciones en la generación de ficheros AUTOCONSUMO

- mesures/mcil345.py
- Cuando se trocea una curva `MCIL345` en ficheros diarios, estos no se deben generar si su contenido queda hueco.
> Evitar generar ficheros diarios MCIL345 sin contenido

- mesures/medidas.py
- spec/generation_files_spec.py
- La propiedad `hours_per_cil` retorna una lista de diccionarios con el recuento de horas para cada CIL presente en el fichero generado.
- Improves #47
> Se ha añadido una propiedad para contar las horar por CIL en el fichero MEDIDAS

- mesures/f1.py
- La generación de los F1 no necesita los campos de bit de calidad.
- Si los datos no contienen los campos de bit de calidad, falla la generación del F1
> FIX No se necesitan los campos de calidad para generar los F1's

- mesures/a5d.py
- mesures/agrecl.py
- mesures/almacenacau.py
- mesures/autoconsumo.py
- mesures/b5d.py
- mesures/cilcau.py
- mesures/cildat.py
- mesures/cumpelectro.py
- mesures/cupscau.py
- mesures/cupsdat.py
- mesures/cupselectro.py
- mesures/enelectroaut.py
- mesures/f1.py
- mesures/f3.py
- mesures/f5.py
- mesures/f5d.py
- mesures/mcil345.py
- mesures/medidas.py
- mesures/p1.py
- mesures/p1d.py
- mesures/p2d.py
- mesures/p5d.py
- mesures/pmest.py
- mesures/potelectro.py
- mesures/utils.py
- Permitir mediante un parámetro opcional, retornar un fichero ZIP conteniendo un `MEDIDAS` por cada Unidad de Programación (representante) de los CIL cuya curva llega a la generación.
- Se ha creado un fichero de utilidades para mantener la compatibilidad entre versiones de `Python` y de `Pandas`.
> Permitir generar el fichero MEDIDAS agrupando los CIL por Unidad de Programación

- mesures/autoconsumo.py
- spec/generation_files_spec.py
- Corregir el formato de comunicación del subgrupo en los ficheros AUTOCONSUMO.
- Este dato se obtiene de la tecnología del generador asociado a la instalación.
- Corregir el formato de comunicación del sistema de anti-vertido en los ficheros AUTOCONSUMO.
- Se debe expresar con un único carácter, en vez de con dos.  
- El subgrupo se informa con los dos primeros carácteres y sin puntos.
- El sistema antivertido se informa con dos carácteres.
- El subgrupo se informa completo, con los tres carácteres separados por un punto.
- El sistema antivertido se informa con un carácter.
> Actualizaciones en la generación del fichero AUTOCONSUMO

- README.md
- mesures/mcil345qh.py
- spec/generation_files_spec.py
- Añadir a la librería el soporte para el fichero `MCIL345QH`, que comunica a REE, en formato de curva cuarto-horaria, las medidas de instalaciones de `Autoconsumo` y de producción de energía eléctrica a partir de fuentes de energía renovables, cogeneración y residuos (`RECORE`) de tipo 3, 4 y 5.
- From https://github.com/gisce/erp/issues/17176
> Nuevo fichero de medidas MCIL345QH para RECORE y Autoconsumos

- README.md
- mesures/f1qh.py
- spec/generation_files_spec.py
- Añadir a la librería el soporte para el fichero `F1QH`, que comunica a REE, en formato de curva cuarto-horaria, las medidas de los suministros de tipo 1, 2 y 3.
- From https://github.com/gisce/erp/issues/17176
> Nuevo fichero de medidas F1QH para suministros de Tipo 1, 2 y 3

- .github/workflows/python2.7-app.yml
- mesures/cumpelectro.py
- mesures/cupselectro.py
- mesures/enelectroaut.py
- mesures/potelectro.py
- spec/generation_files_spec.py
- Se han hecho correcciones en el tratamiento de los ficheros `CUPSELECTRO`, `CUMPELECTRO`, `POTELECTRO` y `ENELECTROAUT`.
- Se han actualizado los `tests` de los cuatro ficheros.
- Se ha arreglado el testeo en `Python 2.7`.
- Los ficheros no soportan sistema de versionado.
- Los ficheros se exportan en formato de fichero ZIP.
- Los ficheros soportan sistema de versionado.
- Los ficheros se exportan en formato de fichero BZ2 o, en caso de ajustarse por parámetro, en formato de fichero plano.
- Fixes https://github.com/gisce/mesures/pull/29
> Correcciones en los ficheros para suministros electrointensivos

- mesures/agrecl.py
- Las bajas de niveles de agregación de un fichero `AGRECL` deben informarse antes que las altas, por si en un mismo fichero hay una baja y un alta del mismo nivel de agregación.
- Las líneas se ordenan de forma ascendente por `origen` y `comercializador`.
- Las líneas se ordenan de forma descendente por `origen` y de forma ascendente por `comercializador`.
> Las bajas de agregacions deben comunicarse antes que las altas de agregaciones en el fichero AGRECL

- mesures/p5d.py
- Se ha añadido un control de versión para que, si existe un fichero con el mismo nombre que el que estamos generando, se incremente en 1 su número de versión para evitar errores al publicarlo.
- Fixes https://github.com/gisce/mesures/pull/5
> Añadir control de versión incremental en la generación de ficheros P5D

- mesures/f5d.py
- spec/generation_files_spec.py
- Añadir, además de la compresión `bz2`, soporte también para fichero `zip`.
- Si se exporta un `F5D` en formato de fichero `zip` no se utiliza el control de versiones.
> Añadir soporte para compresión ZIP en los ficheros F5D

- mesures/reobjeagrecl.py
- mesures/reobjeincl.py
- spec/generation_files_spec.py
- Añadir comentarios en las funciones de `REOBJEX`, aplicar convenciones de valores en campos de DataFrame y modificación de algunos test.
* Related  #67
> Modificar ficheros REOBJEX

- mesures/reobjeagrecl.py
- Los ficheros `REOBJEAGRECL` y `REOBJEINCL` deben soportar caracteres especiales como tildes, eñes, etc.
- No se usa codificación.
- Se usa codificación `iso-8859-15`.
> Añadir codificación de caracteres a los ficheros REOBJEAGRECL y REOBJEINCL

- mesures/cupsdat.py
- mesures/headers.py
- spec/generation_files_spec.py
- Si se indica al crear la clase `CUPSDAT`, el fichero resultante tiene que tener en cuenta el nuevo campo `indicador_envio_medida` indicando si un CUPS publica medida cuartohoraria (`Q`) o no (`H`).
- Implementar tests para mantener el nuevo formato y también el antiguo para periodos previos a noviembre de 2024.
- From https://github.com/gisce/erp/issues/17176
> Ajustes en la generación de ficheros CUPSDAT (ISP Noviembre 2024)

- mesures/f1.py
- mesures/f1qh.py
- spec/generation_files_spec.py
- Permitir mediante un parámetro opcional, generar ficheros `F1` o `F1QH` no estándar, para ser usados fuera de `SIMEL`.
- Requires https://github.com/gisce/mesures/pull/53
> Permitir decimales en ficheros F1 y F1QH

- mesures/f1.py
- mesures/f1qh.py
- spec/generation_files_spec.py
- Los ficheros ZIP que contienen los `F1` o `F1QH` deben mostrar versionado, para identificar al momento la versión de los ficheros contenidos, sin tener que abrir ni descomprimir el ZIP.
- Los ficheros ZIP no tienen versión.
- Los ficheros ZIP tienen versión.
> Mejorar versionado de ficheros F1 y F1QH

- mesures/parsers/dummy_data.py
- mesures/pmest.py
- spec/generation_files_spec.py
- Los ficheros `PMEST` no se generan en el formato esperado. Se debe corregir la pérdida del valor del campo `método de optención`.
- Se implementará una batería de tests para el fichero, como la tienen el resto de ficheros de a librería, para garantizar el formato y el funcionamiento.
- Fixes https://github.com/gisce/erp/pull/12757
> Correcciones en la generación de ficheros PMEST en Distribuidora

- mesures/cupsdat.py
- spec/generation_files_spec.py
- El campo `indicador_envio_medida` debe informarse obligatoriamente en los datos de entrada. No se puede asumir, en caso de no informarse.
- From https://github.com/gisce/mesures/pull/76
> No corregir el tipo de envío de medida en el fichero CUPSDAT

- .github/workflows/python2.7-app.yml
- mesures/cupsdat.py
- Especificar codificación de caracteres `iso-8859-15` en la generación de ficheros `CUPSDAT` dado que estos incluyen un campo "descripción" que puede contener caracteres especiales, dado que se informa el nombre del titular.
- Extra: Se ha arreglado la batería de tests de "Python 2.7", haciéndola ejecutarse sobre `Ubuntu 22.04`.
> Usar codificación ISO-8859-15 en la generación de ficheros CUPSDAT

- mesures/f5d.py
- spec/generation_files_spec.py
- Implementar los nuevos formatos marcados por la CNMC conforme al ATR 3.0
- Un único formato que queda obsoleto con la entrada en vigor de ATR 3.0
- Se ha adaptado el F5D para poder discernir entre el formato a generar (CNMC o REE):
- Se han incluido nuevas magnitudes `ai_fix` y `ao_fix`.
- Se han hecho modificaciones para incluir o no estas magnitudes según el formato a exportar.
> Adapt to new CNMC F5D format

- mesures/f5d.py
- Los ficheros F5D generados no són correctos cuando se comprimen con ZIP.
- Se generaban ficheros no f5d
- Se generan F5D's comprimidos con zip con el formato correcto
fixes #62
> FIX Corregir la generación de F5D's cuando se comprime el F5D con zip

- mesures/f5d.py
- spec/generation_files_spec.py
- Corregir las magnitudes para el formato `CNCM` cambiando `ao_fix` por `ae_fix`
Bug Origin: 
* https://github.com/gisce/mesures/pull/82
> FIX F5D magnitudes de energia saliente fix

- .github/pull_request_template.md
- mesures/f1.py
- mesures/f1qh.py
- mesures/f5d.py
- mesures/mcil345.py
- mesures/mcil345qh.py
- mesures/p1.py
- mesures/p1d.py
- mesures/p2.py
- mesures/p2d.py
- mesures/p5d.py
- spec/generation_files_spec.py
- Mejorar el tratamiento del versionado de ficheros para que al generar ficheros ZIP, tanto el propio ZIP como los ficheros contenidos tengan un versionado correcto y robusto, evitando colisiones con ficheros generados previamente.
- Implementar nuevos tests para garantizar el correcto funcionamiento.
- F1
- F1QH
- F5D
- MCIL345
- MCIL345QH
- P1
- P1D
- P2D
- P5D
- Extra:
- Se ha corregido la máscara del nombre del fichero `P2D` (no debe incluir la fecha del período, a pesar de la documentación de SIMEL, sólo debe incluir la fecha de generación).
- Se ha actualizado la plantilla de las "pull-requests".
- Si el fichero es ZIP, tanto el ZIP como los ficheros contenidos usan el mismo versionado.
- Si el fichero es ZIP, se controlan de forma independiente las versiones del ZIP y de los …
> Mejoras en el versionado de los ficheros
